import { DeviceConfig } from './types';

export const DEVICES: DeviceConfig[] = [
  // iOS Devices
  {
    id: 'iphone-15-pro',
    name: 'iPhone 15 Pro',
    platform: 'ios',
    type: 'mobile',
    width: 393,
    height: 852,
    borderRadius: 50,
    bezel: 10,
    notchType: 'island',
    islandWidth: 120,
    islandHeight: 32,
    homeBar: true,
  },
  {
    id: 'iphone-15',
    name: 'iPhone 15',
    platform: 'ios',
    type: 'mobile',
    width: 393,
    height: 852,
    borderRadius: 48,
    bezel: 11,
    notchType: 'island',
    islandWidth: 120,
    islandHeight: 32,
    homeBar: true,
  },
  {
    id: 'iphone-15-pro-max',
    name: 'iPhone 15 Pro Max',
    platform: 'ios',
    type: 'mobile',
    width: 430,
    height: 932,
    borderRadius: 52,
    bezel: 11,
    notchType: 'island',
    islandWidth: 124,
    islandHeight: 32,
    homeBar: true,
  },
  {
    id: 'iphone-se',
    name: 'iPhone SE',
    platform: 'ios',
    type: 'mobile',
    width: 375,
    height: 667,
    borderRadius: 36,
    bezel: 16,
    notchType: 'none',
    homeBar: false,
  },

  // Android Devices
  {
    id: 'pixel-8-pro',
    name: 'Google Pixel 8 Pro',
    platform: 'android',
    type: 'mobile',
    width: 412,
    height: 915,
    borderRadius: 34,
    bezel: 10,
    notchType: 'punch-hole',
    homeBar: true,
  },
  {
    id: 'pixel-8',
    name: 'Google Pixel 8',
    platform: 'android',
    type: 'mobile',
    width: 412,
    height: 892,
    borderRadius: 32,
    bezel: 10,
    notchType: 'punch-hole',
    homeBar: true,
  },
  {
    id: 'galaxy-s24',
    name: 'Samsung Galaxy S24',
    platform: 'android',
    type: 'mobile',
    width: 412,
    height: 919,
    borderRadius: 30,
    bezel: 9,
    notchType: 'punch-hole',
    homeBar: true,
  },

  // Tablets
  {
    id: 'ipad-pro-11',
    name: 'iPad Pro 11"',
    platform: 'ios',
    type: 'tablet',
    width: 834,
    height: 1194,
    borderRadius: 24,
    bezel: 14,
    notchType: 'none',
    homeBar: true,
  },
  {
    id: 'galaxy-tab-s9',
    name: 'Samsung Galaxy Tab S9',
    platform: 'android',
    type: 'tablet',
    width: 800,
    height: 1280,
    borderRadius: 22,
    bezel: 14,
    notchType: 'none',
    homeBar: true,
  },
];

export const DEFAULT_MOBILE_DEVICE = DEVICES[0]; // iPhone 15 Pro
export const DEFAULT_TABLET_DEVICE = DEVICES.find((d) => d.type === 'tablet') || DEVICES[7];
